Group2/src/main/java/com/csc/group2/entities/DepositTransaction.java
package com.csc.group2.entities;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name = "deposit_transaction")
public class DepositTransaction {
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "transaction_id")
	private int id;

	@Column(name = "depositor_name")
	private String depositorName;

	@Column(name = "depositor_id_card")
	private String depositorIdCard;

	@Column(name = "depositor_address")
	private String depositorAddress;

	@Column(name = "detail")
	private String detail;

	@Column(name = "amount")
	private Double amount;

	@Column(name = "create_date")
	private Date confirmDate;

	@Column(name = "approve_date")
	private Date approveDate;

	@Column(name = "state")
	private String state;

	@ManyToOne
	@JoinColumn(name = "account")
	private AccountInfo account;

	@ManyToOne
	@JoinColumn(name = "bank_branch_id")
	private BankBranch branch;

	@ManyToOne
	@JoinColumn(name = "teller_id")
	private Employee teller;

	@ManyToOne
	@JoinColumn(name = "supervisor_id")
	private Employee supervisor;

	/**
	 * 
	 */
	public DepositTransaction() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param depositorName
	 * @param depositorIdCard
	 * @param depositorAddress
	 * @param detail
	 * @param amount
	 * @param confirmDate
	 * @param approveDate
	 * @param state
	 * @param account
	 * @param branch
	 * @param teller
	 * @param supervisor
	 */
	public DepositTransaction(String depositorName, String depositorIdCard,
			String depositorAddress, String detail, Double amount,
			Date confirmDate, Date approveDate, String state,
			AccountInfo account, BankBranch branch, Employee teller,
			Employee supervisor) {
		super();
		this.depositorName = depositorName;
		this.depositorIdCard = depositorIdCard;
		this.depositorAddress = depositorAddress;
		this.detail = detail;
		this.amount = amount;
		this.confirmDate = confirmDate;
		this.approveDate = approveDate;
		this.state = state;
		this.account = account;
		this.branch = branch;
		this.teller = teller;
		this.supervisor = supervisor;
	}

	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * @return the depositorName
	 */
	public String getDepositorName() {
		return depositorName;
	}

	/**
	 * @param depositorName the depositorName to set
	 */
	public void setDepositorName(String depositorName) {
		this.depositorName = depositorName;
	}

	/**
	 * @return the depositorIdCard
	 */
	public String getDepositorIdCard() {
		return depositorIdCard;
	}

	/**
	 * @param depositorIdCard the depositorIdCard to set
	 */
	public void setDepositorIdCard(String depositorIdCard) {
		this.depositorIdCard = depositorIdCard;
	}

	/**
	 * @return the depositorAddress
	 */
	public String getDepositorAddress() {
		return depositorAddress;
	}

	/**
	 * @param depositorAddress the depositorAddress to set
	 */
	public void setDepositorAddress(String depositorAddress) {
		this.depositorAddress = depositorAddress;
	}

	/**
	 * @return the detail
	 */
	public String getDetail() {
		return detail;
	}

	/**
	 * @param detail the detail to set
	 */
	public void setDetail(String detail) {
		this.detail = detail;
	}

	/**
	 * @return the amount
	 */
	public Double getAmount() {
		return amount;
	}

	/**
	 * @param amount the amount to set
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * @return the confirmDate
	 */
	public Date getConfirmDate() {
		return confirmDate;
	}

	/**
	 * @param confirmDate the confirmDate to set
	 */
	public void setConfirmDate(Date confirmDate) {
		this.confirmDate = confirmDate;
	}

	/**
	 * @return the approveDate
	 */
	public Date getApproveDate() {
		return approveDate;
	}

	/**
	 * @param approveDate the approveDate to set
	 */
	public void setApproveDate(Date approveDate) {
		this.approveDate = approveDate;
	}

	/**
	 * @return the state
	 */
	public String getState() {
		return state;
	}

	/**
	 * @param state the state to set
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * @return the account
	 */
	public AccountInfo getAccount() {
		return account;
	}

	/**
	 * @param account the account to set
	 */
	public void setAccount(AccountInfo account) {
		this.account = account;
	}

	/**
	 * @return the branch
	 */
	public BankBranch getBranch() {
		return branch;
	}

	/**
	 * @param branch the branch to set
	 */
	public void setBranch(BankBranch branch) {
		this.branch = branch;
	}

	/**
	 * @return the teller
	 */
	public Employee getTeller() {
		return teller;
	}

	/**
	 * @param teller the teller to set
	 */
	public void setTeller(Employee teller) {
		this.teller = teller;
	}

	/**
	 * @return the supervisor
	 */
	public Employee getSupervisor() {
		return supervisor;
	}

	/**
	 * @param supervisor the supervisor to set
	 */
	public void setSupervisor(Employee supervisor) {
		this.supervisor = supervisor;
	}

}

Group2/src/main/java/com/csc/group2/entities/InternalPaymentTransaction.java
package com.csc.group2.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Entity implementation class for Entity: InternalPaymentTransaction
 *
 */
/**
 * @author Tu
 *
 */
@Entity
@IdClass(value = PrimaryKey.class)
@Table(name = "internal_payment_transaction")
public class InternalPaymentTransaction implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "transaction_id")
	private int id;
	
	@Id
	@Column(name = "date")
	private Date date;

	@Column(name = "target_name")
	private String receiverName;

	@Column(name = "amount")
	private double amount;

	@Column(name = "create_date")
	private Date confirmDate;

	@Column(name = "approve_date")
	private Date approveDate;

	@Column(name = "state")
	private String state;
	
	@Column(name = "detail")
	private String details;
	
	@ManyToOne
	@JoinColumn(name="source_account_id")
	private AccountInfo sourceAccount;
	
	@ManyToOne
	@JoinColumn(name="target_account_id")
	private AccountInfo targetAccount;
	
	@ManyToOne
	@JoinColumn(name="source_bank_branch_id")
	private BankBranch sourceBankBranch;

	@ManyToOne
	@JoinColumn(name="target_bank_branch_id")
	private BankBranch targetBankBranch;
	
	@ManyToOne
	@JoinColumn(name="teller")
	private Employee teller;
	
	@ManyToOne
	@JoinColumn(name="supervisor")
	private Employee supervisor;

	/**
	 * 
	 */
	public InternalPaymentTransaction() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param id
	 * @param date
	 * @param receiverName
	 * @param amount
	 * @param confirmDate
	 * @param approveDate
	 * @param state
	 * @param details
	 * @param sourceAccount
	 * @param targetAccount
	 * @param sourceBankBranch
	 * @param targetBankBranch
	 * @param teller
	 * @param suppervisor
	 */
	public InternalPaymentTransaction(Date date, String receiverName,
			double amount, Date confirmDate, Date approveDate, String state,
			String details, AccountInfo sourceAccount,
			AccountInfo targetAccount, BankBranch sourceBankBranch,
			BankBranch targetBankBranch, Employee teller, Employee suppervisor) {
		super();
		this.date = date;
		this.receiverName = receiverName;
		this.amount = amount;
		this.confirmDate = confirmDate;
		this.approveDate = approveDate;
		this.state = state;
		this.details = details;
		this.sourceAccount = sourceAccount;
		this.targetAccount = targetAccount;
		this.sourceBankBranch = sourceBankBranch;
		this.targetBankBranch = targetBankBranch;
		this.teller = teller;
		this.supervisor = suppervisor;
	}
	
	/**
	 * @param id
	 * @param receiverName
	 * @param amount
	 * @param confirmDate
	 * @param approveDate
	 * @param state
	 * @param details
	 * @param sourceAccount
	 * @param targetAccount
	 * @param sourceBankBranch
	 * @param targetBankBranch
	 * @param teller
	 * @param suppervisor
	 */
	public InternalPaymentTransaction(int id, String receiverName,
			double amount, Date confirmDate, Date approveDate, String state,
			String details, AccountInfo sourceAccount,
			AccountInfo targetAccount, BankBranch sourceBankBranch,
			BankBranch targetBankBranch, Employee teller, Employee suppervisor) {
		super();
		this.id = id;
		this.receiverName = receiverName;
		this.amount = amount;
		this.confirmDate = confirmDate;
		this.approveDate = approveDate;
		this.state = state;
		this.details = details;
		this.sourceAccount = sourceAccount;
		this.targetAccount = targetAccount;
		this.sourceBankBranch = sourceBankBranch;
		this.targetBankBranch = targetBankBranch;
		this.teller = teller;
		this.supervisor = suppervisor;
	}

	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * @return the date
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * @param date the date to set
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * @return the receiverName
	 */
	public String getReceiverName() {
		return receiverName;
	}

	/**
	 * @param receiverName the receiverName to set
	 */
	public void setReceiverName(String receiverName) {
		this.receiverName = receiverName;
	}

	/**
	 * @return the amount
	 */
	public double getAmount() {
		return amount;
	}

	/**
	 * @param amount the amount to set
	 */
	public void setAmount(double amount) {
		this.amount = amount;
	}

	/**
	 * @return the confirmDate
	 */
	public Date getConfirmDate() {
		return confirmDate;
	}

	/**
	 * @param confirmDate the confirmDate to set
	 */
	public void setConfirmDate(Date confirmDate) {
		this.confirmDate = confirmDate;
	}

	/**
	 * @return the approveDate
	 */
	public Date getApproveDate() {
		return approveDate;
	}

	/**
	 * @param approveDate the approveDate to set
	 */
	public void setApproveDate(Date approveDate) {
		this.approveDate = approveDate;
	}

	/**
	 * @return the state
	 */
	public String getState() {
		return state;
	}

	/**
	 * @param state the state to set
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * @return the details
	 */
	public String getDetails() {
		return details;
	}

	/**
	 * @param details the details to set
	 */
	public void setDetails(String details) {
		this.details = details;
	}

	/**
	 * @return the sourceAccount
	 */
	public AccountInfo getSourceAccount() {
		return sourceAccount;
	}

	/**
	 * @param sourceAccount the sourceAccount to set
	 */
	public void setSourceAccount(AccountInfo sourceAccount) {
		this.sourceAccount = sourceAccount;
	}

	/**
	 * @return the targetAccount
	 */
	public AccountInfo getTargetAccount() {
		return targetAccount;
	}

	/**
	 * @param targetAccount the targetAccount to set
	 */
	public void setTargetAccount(AccountInfo targetAccount) {
		this.targetAccount = targetAccount;
	}

	/**
	 * @return the sourceBankBranch
	 */
	public BankBranch getSourceBankBranch() {
		return sourceBankBranch;
	}

	/**
	 * @param sourceBankBranch the sourceBankBranch to set
	 */
	public void setSourceBankBranch(BankBranch sourceBankBranch) {
		this.sourceBankBranch = sourceBankBranch;
	}

	/**
	 * @return the targetBankBranch
	 */
	public BankBranch getTargetBankBranch() {
		return targetBankBranch;
	}

	/**
	 * @param targetBankBranch the targetBankBranch to set
	 */
	public void setTargetBankBranch(BankBranch targetBankBranch) {
		this.targetBankBranch = targetBankBranch;
	}

	/**
	 * @return the teller
	 */
	public Employee getTeller() {
		return teller;
	}

	/**
	 * @param teller the teller to set
	 */
	public void setTeller(Employee teller) {
		this.teller = teller;
	}

	/**
	 * @return the supervisor
	 */
	public Employee getSupervisor() {
		return supervisor;
	}

	/**
	 * @param suppervisor the suppervisor to set
	 */
	public void setSupervisor(Employee supervisor) {
		this.supervisor = supervisor;
	}

}

Group2/src/main/java/com/csc/group2/entities/WithdrawalTransaction.java
package com.csc.group2.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name = "withdrawal_transaction")
public class WithdrawalTransaction implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "transaction_id")
	private int id;

	@Column(name = "detail")
	private String detail;

	@Column(name = "amount")
	private double amount;

	@Column(name = "create_date")
	private Date confirmDate;

	@Column(name = "approve_date")
	private Date approveDate;

	@Column(name = "date")
	private Date date;

	@Column(name = "state")
	private String state;

	@ManyToOne
	@JoinColumn(name = "account")
	private AccountInfo account;

	@ManyToOne
	@JoinColumn(name = "bankBranch_id")
	private BankBranch branch;

	@ManyToOne
	@JoinColumn(name = "teller")
	private Employee teller;

	@ManyToOne
	@JoinColumn(name = "supervisor")
	private Employee supervisor;

	public WithdrawalTransaction() {
		super();
	}

	/**
	 * @param id
	 * @param detail
	 * @param amount
	 * @param confirmDate
	 * @param approveDateF
	 * @param state
	 * @param account
	 * @param branch
	 * @param teller
	 * @param supervisor
	 */
	public WithdrawalTransaction(int id, String detail, double amount,
			Date confirmDate, Date approveDate, Date date, String state,
			AccountInfo account, BankBranch branch, Employee teller,
			Employee supervisor) {
		super();
		this.id = id;
		this.detail = detail;
		this.amount = amount;
		this.confirmDate = confirmDate;
		this.approveDate = approveDate;
		this.state = state;
		this.account = account;
		this.branch = branch;
		this.teller = teller;
		this.supervisor = supervisor;
		this.date = date;
	}

	public WithdrawalTransaction(String detail, double amount,
			Date confirmDate, Date approveDate, Date date, String state,
			AccountInfo account, BankBranch branch, Employee teller,
			Employee supervisor) {
		super();
		this.detail = detail;
		this.amount = amount;
		this.confirmDate = confirmDate;
		this.approveDate = approveDate;
		this.state = state;
		this.account = account;
		this.branch = branch;
		this.teller = teller;
		this.supervisor = supervisor;
		this.date = date;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDetail() {
		return detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public double getAmount() {
		return amount;
	}
	
	public String getAmountInFigures(){
		
		return String.format("%,.2f", amount);
	}
	

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public Date getConfirmDate() {
		return confirmDate;
	}

	public void setConfirmDate(Date confirmDate) {
		this.confirmDate = confirmDate;
	}

	public Date getApproveDate() {
		return approveDate;
	}

	public void setApproveDate(Date approveDateF) {
		this.approveDate = approveDateF;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public AccountInfo getAccount() {
		return account;
	}

	public void setAccount(AccountInfo account) {
		this.account = account;
	}

	public BankBranch getBranch() {
		return branch;
	}

	public void setBranch(BankBranch branch) {
		this.branch = branch;
	}

	public Employee getTeller() {
		return teller;
	}

	public void setTeller(Employee teller) {
		this.teller = teller;
	}

	public Employee getSupervisor() {
		return supervisor;
	}

	public void setSupervisor(Employee supervisor) {
		this.supervisor = supervisor;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
}

Group2/src/main/webapp/WEB-INF/views/withdrawal-transaction-supervisor.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html>
<html>

<head>
<meta charset="ISO-8859-1">
<title>CSC Banking System</title>
<link rel="stylesheet" href="css/screen.css" type="text/css" />
<link rel="stylesheet" href="css/common.css" type="text/css" />
<link rel="stylesheet" href="css/bootstrap.min.css" type="text/css" />
<link rel="stylesheet" href="css/jquery-ui-min.css" type="text/css" />
<link rel="stylesheet" href="css/jquery.dataTables.css" type="text/css" />

<!-- SCRIPT -->
<script src="js/jquery/jquery-1.4.1.min.js" type="text/javascript"></script>
<script src="js/jquery/jquery.tooltip.js" type="text/javascript"></script>
<script src="js/jquery/jquery-1.10.2.min.js" type="text/javascript"></script>
<script src="js/jquery/jquery-ui.js" type="text/javascript"></script>
<script src="js/jquery/jquery.dataTables.js" type="text/javascript"></script>
<script src="js/bootstrap.min.js" type="text/javascript"></script>


<script type="text/javascript">
	$(document)
			.ready(
					function() {
						
						$("#mytable").dataTable();
						$("#mytable2").dataTable();
						
						var col;
						$('#mytable tbody').on('click','tr',function() {
							var table = $('#mytable').DataTable();
							col = table.row( this ).data();
					        var cntTable = "";
							cntTable = "<tr><th>Id</th><td id=\"id\">" + col[0]
								+ "</td></tr>"
								+ "<tr><th>Account Number</th><td id=\"sourceAccount\">"
								+ col[1] + "</td></tr>"
								+ "<tr><th>Account Name</th><td id=\"sourceAccount\">" + col[2]
								+ "</td></tr>" + "<tr><th>Branch</th><td id=\"sourceAccount\">"
								+ col[3] + "</td></tr>"
								+ "<tr><th>Balance</th><td id=\"sourceBranch\">" + col[4]
								+ "</td></tr>" + "<tr><th>Amount</th><td id=\"targetAccount\">"
								+ col[5] + "</td></tr>"
								+ "<tr><th>Detail</th><td id=\"targetBranch\">" + col[6]
								+ "</td></tr>"
								+ "<tr><th>Confirmed Time</th><td id=\"amount\">" + col[7]
								+ "</td></tr>" + "<tr><th>State</th><td id=\"createDate\">"
								+ col[9] + "</td></tr>"
								+ "<tr><th>Teller</th><td id=\"state\">" + col[10]
								+ "</td></tr>";
							$("#myNewTable").html(cntTable);
					        $('#myModal').modal('show');
						});

						$('#approve').on('click',function() {
							window.location.href = "approveWithdrawalTransaction.html?transactionId=" + col[0];
						});

						$('#reject').on('click',function() {
							window.location.href = "rejectWithdrawalTransaction.html?transactionId=" + col[0];
						});		
						
						$('#show').click(function() {
							$("#history").show();
						});
						
						$('#hide').click(function() {
							$("#history").hide();
						});
						
					});
</script>

</head>

<body>
	<div id="page-top-outer">
		<div class="logout">
			Welcome to <span class="loginName">${employee.loginId}</span> | <a
				href="home.html">Logout</a>
		</div>
		<div id="page-center" style="background-color: white;">

			<!-- start logo -->
			<div id="logo" style="padding-left: 50px">
				<a href=""><img src="images/logo.png" width="229" height="74"
					alt="" /></a>
			</div>

		</div>
	</div>

	<div class="nav-outer-repeat">

		<nav class="navbar navbar-inverse">
			<div class="container-fluid">
				<div class="navbar-header" style="width: 80px; height: 37px;">
				</div>
				<div>
					<ul style="width: 700px;" class="nav navbar-nav">

						<li><a href="supervisor-deposit-transaction.html">Deposit
								Transaction</a></li>
						<li><a href="supervisor-internal-payment-transaction.html">Internal
								Payment Transaction</a></li>
						<li><a href="withdrawal-transaction.html">Withdrawal
								Transaction</a></li>
					</ul>
				</div>
			</div>
		</nav>
	</div>

	<div id="content-outer">
		<!-- start content -->
		<div id="content">

			<!--  start page-heading -->
			<table border="0" width="100%" cellpadding="0" cellspacing="0"
				id="content-table">
				<tr>
					<th rowspan="3" class="sized"><img
						src="images/shared/side_shadowleft.jpg" width="20" height="300"
						alt="" /></th>
					<th class="topleft"></th>
					<td id="tbl-border-top">&nbsp;</td>
					<th class="topright"></th>
					<th rowspan="3" class="sized"><img
						src="images/shared/side_shadowright.jpg" width="20" height="300"
						alt="" /></th>
				</tr>
				<tr>
					<td id="tbl-border-left"></td>
					<td>
						<div id="content-table-inner">
							<div id="page-heading" align="center">
								<h1>Approve Withdrawal Information</h1>
							</div>
							<div align="center" style="padding-top: 15px;">
								<table>
									<tr>
										<th><label>Date:</label></th>
										<td><label>${toDate}</label></td>
									</tr>
								</table>
							</div>
							<div id="content-table-inner" style="padding: 50px 35px 0px 35px;">
								<table id="mytable" class="table table-hover table-bordered table-striped">
									<thead>
										<tr>
											<th>Id</th>
											<th>Account Number</th>
											<th>Account Name</th>
											<th>Branch</th>
											<th>Balance</th>
											<th>Amount</th>
											<th>Detail</th>
											<th>Create Date</th>
<!-- 											<th>Approve Date</th> -->
											<th>State</th>
											<th>Teller</th>
										</tr>
									</thead>
									<tbody>
										<c:forEach var="withdrawTrans" items="${listPending}">
											<tr>
												<td>${withdrawTrans.id}</td>
												<td>${withdrawTrans.account.accountNumber}</td>
												<td>${withdrawTrans.account.fullName}</td>
												<td>${withdrawTrans.branch.branchName}</td>
												<td><fmt:formatNumber type="number" maxFractionDigits="3" value="${withdrawTrans.account.balance}" /></td>
												<td>${withdrawTrans.amountInFigures}</td>
												<td>${withdrawTrans.detail}</td>
												<td><fmt:formatDate type="both" value="${withdrawTrans.confirmDate}" /></td>
<%-- 												<td>${withdrawTrans.approveDate}</td> --%>
												<td>${withdrawTrans.state}</td>
												<td>${withdrawTrans.teller.fullName}</td>
											</tr>
										</c:forEach>
									</tbody>
								</table>
								
								<button class="btnAdd" id="show" type="button" >Show</button>
								<button class="btnAdd" id="hide" type="button" >Hide</button>
								
								<div hidden="hidden" id="history">
									<div align="center"
										style="padding-top: 15px; padding-bottom: 25px;">
										<div align="center">
											<h1>Approve Withdrawal Transaction History</h1>
										</div>
									</div>
	
									<table id="mytable2" class="table table-hover table-bordered table-striped">
										<thead>
										<tr>
											<th>Id</th>
											<th>Account Number</th>
											<th>Account Name</th>
											<th>Branch</th>
											<th>Balance</th>
											<th>Amount</th>
											<th>Detail</th>
											<th>Create Date</th>
											<th>Approve Date</th>
											<th>State</th>
											<th>Teller</th>
										</tr>
									</thead>
									<tbody>
										<c:forEach var="withdrawTrans" items="${listApproved}">
											<tr>
												<td>${withdrawTrans.id}</td>
												<td>${withdrawTrans.account.accountNumber}</td>
												<td>${withdrawTrans.account.fullName}</td>
												<td>${withdrawTrans.branch.branchName}</td>
												<td><fmt:formatNumber type="number" maxFractionDigits="3" value="${withdrawTrans.account.balance}" /></td>
												<td>${withdrawTrans.amountInFigures}</td>
												<td>${withdrawTrans.detail}</td>
												<td><fmt:formatDate type="both" value="${withdrawTrans.confirmDate}" /></td>
												<td>${withdrawTrans.approveDate}</td>
												<td>${withdrawTrans.state}</td>
												<td>${withdrawTrans.teller.fullName}</td>
											</tr>
										</c:forEach>
									</tbody>
									</table>
								</div>
							</div>

							<!-- Modal -->
							<div class="modal fade" id="myModal" role="dialog">
								<div class="modal-dialog">

									<!-- Modal content-->
									<div class="modal-content">
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal">&times;</button>
											<h4 class="modal-title">Withdrawal Transaction Infomation</h4>
										</div>
										<div class="modal-body">
											<table class="table table-hover table-bordered table-striped" id="myNewTable">
												
											</table>
										</div>
										<div class="modal-footer">
											<button type="button" id="approve" class="btn btn-primary" data-dismiss="modal">Approve</button>
											<button type="button" id="reject" class="btn btn-primary" data-dismiss="modal">Reject</button>
											<button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
										</div>
									</div>

								</div>
							</div>
						</div>
					</td>
					<td id="tbl-border-right"></td>
				</tr>
				<tr>
					<th class="sized bottomleft"></th>
					<td id="tbl-border-bottom">&nbsp;</td>
					<th class="sized bottomright"></th>
				</tr>
			</table>

			<br />
		</div>
		<div class="clear">&nbsp;</div>
	</div>

	<div class="clear">&nbsp;</div>

	<!-- start footer -->
	<div id="footer">
		<!--  start footer-left -->
		<div id="footer-left">
			&copy; Copyright 2014 DAOnJPA| Java Fresher Training Program. <span
				id="spanYear"></span> <a href="http://www.csc.com" target="_blank">www.csc.com</a>
		</div>
		<!--  end footer-left -->
		<div class="clear">&nbsp;</div>
	</div>
</body>

</html>